import { FoodRecord } from './types';

/** Mock 食物記錄資料 — Demo 模式使用 */
export const MOCK_FOOD_RECORDS: FoodRecord[] = [
  {
    id: 'mock-1',
    foodName: '雞腿便當',
    items: [
      { name: '炸雞腿', calories: 350, protein: 28, carbs: 12, fat: 22, fiber: 0, portion: '1隻約150g', confidence: '中' },
      { name: '白飯', calories: 280, protein: 5, carbs: 62, fat: 0.5, fiber: 0.5, portion: '1碗約200g', confidence: '高' },
      { name: '滷蛋', calories: 80, protein: 6, carbs: 1, fat: 5, fiber: 0, portion: '1顆', confidence: '高' },
      { name: '青菜', calories: 30, protein: 2, carbs: 4, fat: 1, fiber: 2, portion: '一份約80g', confidence: '中' },
    ],
    totalCalories: 740,
    totalProtein: 41,
    totalCarbs: 79,
    totalFat: 28.5,
    totalFiber: 2.5,
    mealType: '午餐',
    source: '便當',
    restaurantName: '',
    date: new Date().toISOString().split('T')[0],
    note: '',
    overallConfidence: '中',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    foodName: '麥當勞大麥克套餐',
    items: [
      { name: '大麥克', calories: 563, protein: 26, carbs: 44, fat: 33, fiber: 3, portion: '1個', confidence: '高' },
      { name: '中薯', calories: 340, protein: 4, carbs: 44, fat: 16, fiber: 4, portion: '1份', confidence: '高' },
      { name: '可口可樂(中)', calories: 150, protein: 0, carbs: 39, fat: 0, fiber: 0, portion: '480ml', confidence: '高' },
    ],
    totalCalories: 1053,
    totalProtein: 30,
    totalCarbs: 127,
    totalFat: 49,
    totalFiber: 7,
    mealType: '午餐',
    source: '餐廳',
    restaurantName: '麥當勞',
    date: new Date().toISOString().split('T')[0],
    note: '官方營養資訊',
    overallConfidence: '高',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    foodName: '鮪魚三明治 + 拿鐵',
    items: [
      { name: '鮪魚三明治', calories: 320, protein: 18, carbs: 30, fat: 14, fiber: 2, portion: '1份', confidence: '中' },
      { name: '拿鐵咖啡', calories: 180, protein: 8, carbs: 15, fat: 9, fiber: 0, portion: '大杯480ml', confidence: '中' },
    ],
    totalCalories: 500,
    totalProtein: 26,
    totalCarbs: 45,
    totalFat: 23,
    totalFiber: 2,
    mealType: '早餐',
    source: '超商',
    restaurantName: '7-ELEVEN',
    date: new Date().toISOString().split('T')[0],
    note: '',
    overallConfidence: '中',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    foodName: '水果沙拉',
    items: [
      { name: '蘋果', calories: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, portion: '半顆約100g', confidence: '中' },
      { name: '香蕉', calories: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, portion: '1根約100g', confidence: '中' },
      { name: '藍莓', calories: 28, protein: 0.4, carbs: 7, fat: 0.2, fiber: 1.2, portion: '一把約50g', confidence: '低' },
      { name: '優格醬', calories: 60, protein: 3, carbs: 8, fat: 2, fiber: 0, portion: '2湯匙', confidence: '中' },
    ],
    totalCalories: 229,
    totalProtein: 4.8,
    totalCarbs: 52,
    totalFat: 2.7,
    totalFiber: 6.2,
    mealType: '點心',
    source: '自煮',
    restaurantName: '',
    date: (() => { const d = new Date(); d.setDate(d.getDate() - 1); return d.toISOString().split('T')[0]; })(),
    note: '',
    overallConfidence: '中',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-5',
    foodName: '牛肉麵',
    items: [
      { name: '牛肉', calories: 250, protein: 26, carbs: 0, fat: 15, fiber: 0, portion: '約120g', confidence: '中' },
      { name: '拉麵條', calories: 320, protein: 10, carbs: 62, fat: 3, fiber: 2, portion: '一球約200g', confidence: '中' },
      { name: '湯底', calories: 80, protein: 4, carbs: 6, fat: 4, fiber: 0, portion: '約300ml', confidence: '低' },
      { name: '青蔥/青菜', calories: 15, protein: 1, carbs: 2, fat: 0.2, fiber: 1, portion: '適量', confidence: '低' },
    ],
    totalCalories: 665,
    totalProtein: 41,
    totalCarbs: 70,
    totalFat: 22.2,
    totalFiber: 3,
    mealType: '晚餐',
    source: '餐廳',
    restaurantName: '',
    date: (() => { const d = new Date(); d.setDate(d.getDate() - 1); return d.toISOString().split('T')[0]; })(),
    note: '',
    overallConfidence: '低',
    createdAt: new Date().toISOString(),
  },
];
